import { z } from "zod";
import {
  patientMatchResultSchema,
  patientProcessingStatusSchema,
  qaOutcomeSchema,
} from "./batch-pipeline";
import { emptyOasisQaSummary, oasisQaSummarySchema } from "./oasis-qa";
import { patientEpisodeWorkItemSchema } from "./patient-episode-work-item";
import { patientWorkflowRunSchema } from "./patient-workflow-run";

export const patientDashboardArtifactPathsSchema = z.object({
  codingInput: z.string().min(1),
  documentText: z.string().min(1),
  documentFactPack: z.string().min(1).nullable().default(null).optional(),
  documentCatalog: z.string().min(1).nullable().default(null).optional(),
  qaPrefetch: z.string().min(1).nullable(),
  patientQaReference: z.string().min(1),
  qaDocumentSummary: z.string().min(1),
  fieldMapSnapshot: z.string().min(1),
  referralIntakeState: z.string().min(1).nullable().default(null).optional(),
  referralSourceDocumentsManifest: z.string().min(1).nullable().default(null).optional(),
  referralDocumentResultsManifest: z.string().min(1).nullable().default(null).optional(),
  patientPortalStatusSnapshot: z.string().min(1).nullable().default(null).optional(),
  printedNoteChartValues: z.string().min(1).nullable(),
  printedNoteReview: z.string().min(1).nullable(),
  oasisDiagnosisExtraction: z.string().min(1).nullable().default(null).optional(),
  referralDiagnosisExtraction: z.string().min(1).nullable().default(null).optional(),
  diagnosisReconciliation: z.string().min(1).nullable().default(null).optional(),
  clinicalComparisonRows: z.string().min(1).nullable().default(null).optional(),
  artifactLineage: z.string().min(1).nullable().default(null).optional(),
  sourceClinicalFactPack: z.string().min(1).nullable().default(null).optional(),
  oasisClinicalFactPack: z.string().min(1).nullable().default(null).optional(),
  clinicalFactPackManifest: z.string().min(1).nullable().default(null).optional(),
  oasisExtractionCoverageReport: z.string().min(1).nullable().default(null).optional(),
  clinicalContradictionAnalysis: z.string().min(1).nullable().default(null).optional(),
  planOfCareDiagnosisSource: z.string().min(1).nullable().default(null).optional(),
  planOfCareCandidates: z.string().min(1).nullable().default(null).optional(),
  planOfCareReviewDraft: z.string().min(1).nullable().default(null).optional(),
  planOfCareReviewSummary: z.string().min(1).nullable().default(null).optional(),
  visitNotesDiscovery: z.string().min(1).nullable().default(null).optional(),
  visitNoteProcessingManifest: z.string().min(1).nullable().default(null).optional(),
  visitNoteFactPack: z.string().min(1).nullable().default(null).optional(),
  visitNoteQaReview: z.string().min(1).nullable().default(null).optional(),
  llmUsageAudit: z.string().min(1).nullable().default(null).optional(),
  oasisValidation: z.string().min(1).nullable().default(null).optional(),
  referralOasisConsistency: z.string().min(1).nullable().default(null).optional(),
  oasisGate: z.string().min(1).nullable().default(null).optional(),
  generatedPlanOfCare: z.string().min(1).nullable().default(null).optional(),
  oasisDomSectionProcessingManifest: z.string().min(1).nullable().default(null).optional(),
  oasisDomSectionOutputs: z.string().min(1).nullable().default(null).optional(),
  oasisAssessmentProcessingManifest: z.string().min(1).nullable().default(null).optional(),
  patientRunCacheSummary: z.string().min(1).nullable().default(null).optional(),
});

export type PatientDashboardArtifactPaths = z.infer<typeof patientDashboardArtifactPathsSchema>;

export const patientDashboardArtifactContentsSchema = z.object({
  codingInput: z.unknown().nullable(),
  documentText: z.unknown().nullable(),
  documentFactPack: z.unknown().nullable().default(null).optional(),
  documentCatalog: z.unknown().nullable().default(null).optional(),
  qaPrefetch: z.unknown().nullable(),
  patientQaReference: z.unknown().nullable(),
  qaDocumentSummary: z.unknown().nullable(),
  fieldMapSnapshot: z.unknown().nullable(),
  referralIntakeState: z.unknown().nullable().default(null).optional(),
  referralSourceDocumentsManifest: z.unknown().nullable().default(null).optional(),
  referralDocumentResultsManifest: z.unknown().nullable().default(null).optional(),
  referralDocumentArtifacts: z.unknown().nullable().default(null).optional(),
  patientPortalStatusSnapshot: z.unknown().nullable().default(null).optional(),
  printedNoteChartValues: z.unknown().nullable(),
  printedNoteReview: z.unknown().nullable(),
  oasisDiagnosisExtraction: z.unknown().nullable().default(null).optional(),
  referralDiagnosisExtraction: z.unknown().nullable().default(null).optional(),
  diagnosisReconciliation: z.unknown().nullable().default(null).optional(),
  clinicalComparisonRows: z.unknown().nullable().default(null).optional(),
  artifactLineage: z.unknown().nullable().default(null).optional(),
  sourceClinicalFactPack: z.unknown().nullable().default(null).optional(),
  oasisClinicalFactPack: z.unknown().nullable().default(null).optional(),
  clinicalFactPackManifest: z.unknown().nullable().default(null).optional(),
  oasisExtractionCoverageReport: z.unknown().nullable().default(null).optional(),
  clinicalContradictionAnalysis: z.unknown().nullable().default(null).optional(),
  planOfCareDiagnosisSource: z.unknown().nullable().default(null).optional(),
  planOfCareCandidates: z.unknown().nullable().default(null).optional(),
  planOfCareReviewDraft: z.unknown().nullable().default(null).optional(),
  planOfCareReviewSummary: z.unknown().nullable().default(null).optional(),
  visitNotesDiscovery: z.unknown().nullable().default(null).optional(),
  visitNoteProcessingManifest: z.unknown().nullable().default(null).optional(),
  visitNoteFactPack: z.unknown().nullable().default(null).optional(),
  visitNoteQaReview: z.unknown().nullable().default(null).optional(),
  llmUsageAudit: z.unknown().nullable().default(null).optional(),
  oasisValidation: z.unknown().nullable().default(null).optional(),
  referralOasisConsistency: z.unknown().nullable().default(null).optional(),
  oasisGate: z.unknown().nullable().default(null).optional(),
  generatedPlanOfCare: z.unknown().nullable().default(null).optional(),
  oasisDomSectionProcessingManifest: z.unknown().nullable().default(null).optional(),
  oasisDomSectionOutputs: z.unknown().nullable().default(null).optional(),
  oasisAssessmentProcessingManifest: z.unknown().nullable().default(null).optional(),
  oasisAssessmentArtifacts: z.unknown().nullable().default(null).optional(),
  patientRunCacheSummary: z.unknown().nullable().default(null).optional(),
});

export type PatientDashboardArtifactContents = z.infer<typeof patientDashboardArtifactContentsSchema>;

export type PatientDashboardChangeSummary = Record<string, unknown>;

export const patientDashboardStateSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string().min(1),
  batchId: z.string().min(1),
  patientId: z.string().min(1),
  runId: z.string().min(1),
  subsidiaryId: z.string().min(1).default("default"),
  patientName: z.string().min(1),
  processingStatus: patientProcessingStatusSchema,
  executionStep: z.string().min(1),
  progressPercent: z.number().min(0).max(100),
  startedAt: z.string().min(1),
  completedAt: z.string().min(1).nullable(),
  lastUpdatedAt: z.string().min(1),
  matchResult: patientMatchResultSchema,
  qaOutcome: qaOutcomeSchema,
  oasisQaSummary: oasisQaSummarySchema.default(emptyOasisQaSummary),
  artifactCount: z.number().int().nonnegative(),
  hasFindings: z.boolean(),
  bundleAvailable: z.boolean(),
  resultBundlePath: z.string().min(1).nullable(),
  logPath: z.string().min(1).nullable(),
  errorSummary: z.string().min(1).nullable(),
  workItem: patientEpisodeWorkItemSchema.nullable(),
  workflowRuns: z.array(patientWorkflowRunSchema).default([]),
  artifactPaths: patientDashboardArtifactPathsSchema,
  artifactContents: patientDashboardArtifactContentsSchema,
});

export type PatientDashboardState = z.infer<typeof patientDashboardStateSchema>;
