export const DISCOVERY_SELECTORS = {
  topNavContainers: ['header nav', '[role="banner"] nav', '[role="navigation"]', "nav"],
  sideNavContainers: [
    'aside nav',
    'aside',
    '[class*="sidebar"]',
    '[class*="Sidebar"]',
    '[class*="sidenav"]',
    '[class*="SideNav"]',
  ],
  navItemSelectors: ['a', 'button', '[role="link"]', '[role="button"]'],
  searchInputSelectors: [
    'input[type="search"]',
    'input[placeholder*="Search"]',
    'input[placeholder*="search"]',
    'input[aria-label*="Search"]',
    'input[aria-label*="search"]',
    'input[placeholder*="Filter"]',
    'input[placeholder*="filter"]',
    'input[aria-label*="Filter"]',
    'input[aria-label*="filter"]',
    '[role="searchbox"]',
  ],
  searchContainerSelectors: [
    '[role="search"]',
    '[class*="search"]',
    '[class*="Search"]',
    'form',
  ],
  widgetContainers: [
    '[class*="widget"]',
    '[class*="Widget"]',
    '[class*="panel"]',
    '[class*="Panel"]',
    '[class*="module"]',
    '[class*="Module"]',
  ],
  tileContainers: [
    'main a',
    'main button',
    '[role="link"]',
    '[role="button"]',
    '[class*="tile"]',
    '[class*="Tile"]',
    '[class*="card"]',
    '[class*="Card"]',
    '[class*="dashboard"] [class*="item"]',
    '[class*="dashboard"] [class*="Item"]',
    '[class*="widget"]',
    '[class*="Widget"]',
  ],
  sectionGroupContainers: [
    'main section',
    'main article',
    'main [role="region"]',
    'main [class*="section"]',
    'main [class*="Section"]',
    'main [class*="panel"]',
    'main [class*="Panel"]',
    'main [class*="widget"]',
    'main [class*="Widget"]',
    'main [class*="card"]',
    'main [class*="Card"]',
  ],
  containerHeadingSelectors: [
    'h1',
    'h2',
    'h3',
    'h4',
    '[role="heading"]',
    '[class*="title"]',
    '[class*="Title"]',
    '[class*="header"]',
    '[class*="Header"]',
    '[data-testid*="title"]',
    'header',
  ],
  sectionHeaderSelectors: [
    'main h1',
    'main h2',
    'main h3',
    'main h4',
    'section h2',
    'section h3',
    'section h4',
    'legend',
    '[role="heading"]',
  ],
  buttonSelectors: [
    'button',
    'a',
    '[role="button"]',
    '[role="link"]',
    '[role="tab"]',
  ],
  tableSelectors: ['table', '[role="table"]', '[role="grid"]'],
  formSelectors: ['form', '[role="form"]'],
  tabSelectors: ['[role="tab"]', '[class*="tab"]', '[class*="Tab"]'],
  cardSelectors: [
    '[class*="card"]',
    '[class*="Card"]',
    '[class*="tile"]',
    '[class*="Tile"]',
    '[class*="widget"]',
    '[class*="Widget"]',
    'article',
    '[role="article"]',
  ],
  modalSelectors: [
    '[role="dialog"]',
    '[aria-modal="true"]',
    '[class*="modal"]',
    '[class*="Modal"]',
  ],
  layoutPatterns: {
    tabs: ['[role="tablist"]', '[role="tab"]', '[class*="tabs"]', '[class*="Tabs"]'],
    accordions: ['[aria-expanded]', '[class*="accordion"]', '[class*="Accordion"]'],
    cards: ['[class*="card"]', '[class*="Card"]', '[class*="tile"]', '[class*="Tile"]'],
    tables: ['table', '[role="table"]', '[role="grid"]'],
    splitPanes: ['[class*="split"]', '[class*="Split"]', '[class*="pane"]', '[class*="Pane"]'],
    forms: ['form', '[role="form"]', '[role="search"]'],
  },
} as const;
