export const DOCUMENT_EXTRACTION_SELECTORS = {
  pageTitleSelectors: [
    "main h1",
    "main h2",
    '[role="heading"][aria-level="1"]',
    '[role="heading"][aria-level="2"]',
    '[class*="page-title"]',
    '[class*="PageTitle"]',
    '[class*="title"]',
    '[class*="Title"]',
  ],
  headingSelectors: [
    "main h1",
    "main h2",
    "main h3",
    "section h2",
    "section h3",
    '[role="heading"]',
    "legend",
    '[class*="heading"]',
    '[class*="Heading"]',
    '[class*="title"]',
    '[class*="Title"]',
  ],
  fieldLabelSelectors: [
    "label",
    "dt",
    "th",
    '[class*="label"]',
    '[class*="Label"]',
    '[class*="field-name"]',
    '[class*="FieldName"]',
  ],
  statusSelectors: [
    '[class*="status"]',
    '[class*="Status"]',
    '[class*="signature"]',
    '[class*="Signature"]',
    '[class*="validation"]',
    '[class*="Validation"]',
    '[data-testid*="status"]',
    '[data-testid*="signature"]',
    'text=/signed|unsigned|validated|validation|pending signature/i',
  ],
  sectionRootSelectors: [
    "section",
    "article",
    '[role="region"]',
    '[class*="section"]',
    '[class*="Section"]',
    '[class*="panel"]',
    '[class*="Panel"]',
    '[class*="card"]',
    '[class*="Card"]',
    "fieldset",
    "form",
  ],
  headingLikeSelectors: [
    "h1",
    "h2",
    "h3",
    "h4",
    "legend",
    '[role="heading"]',
    '[class*="heading"]',
    '[class*="Heading"]',
    '[class*="title"]',
    '[class*="Title"]',
    "label",
    "dt",
    "th",
  ],
  valueSelectors: [
    "dd",
    "td",
    '[class*="value"]',
    '[class*="Value"]',
    '[class*="content"]',
    '[class*="Content"]',
  ],
  patientIdLabelPattern: /\b(mrn|medical record|patient id|record id|client id)\b/i,
  visitDateLabelPattern: /\b(visit date|date of visit|service date|dos|assessment date|soc date|order date)\b/i,
  physicianLabelPattern: /\b(physician|allowed practitioner|provider|doctor|ordered by|signed by)\b/i,
  signatureSignedPattern: /\b(signed|electronically signed|completed and signed)\b/i,
  signatureUnsignedPattern: /\b(unsigned|not signed|signature required|pending signature)\b/i,
  signatureValidatedPattern: /\b(validated|locked|finalized)\b/i,
  visitNoteUrlPattern: /\/documents\/note\/visitnote\//i,
  oasisUrlPattern: /\/documents\/(?:assessment|oasis)\//i,
  planOfCareUrlPattern: /\/documents\/(?:planofcare|plan-of-care|poc)\//i,
  admissionOrderUrlPattern: /\/documents\/(?:order|orders)\/(?:admission|admit)\b/i,
  physicianOrderUrlPattern: /\/documents\/(?:order|orders)\//i,
} as const;
