export const HUB_CARD_SELECTORS = {
  cardCandidateSelectors: [
    "main .shortcut-item",
    'main [class*="shortcut-item"]',
    'main [class*="card"]',
    'main [class*="Card"]',
    'main [class*="tile"]',
    'main [class*="Tile"]',
    'main [class*="cursor-pointer"]',
    "main button",
    "main a",
  ],
  interactiveDescendantSelectors: [
    "a[href]",
    "button",
    '[role="button"]',
    '[role="link"]',
    '[tabindex]:not([tabindex="-1"])',
    '[class*="cursor-pointer"]',
    '[class*="shortcut-item"]',
    '[style*="cursor: pointer"]',
  ],
  headingSelectors: [
    "h1",
    "h2",
    "h3",
    "h4",
    '[role="heading"]',
    '[class*="title"]',
    '[class*="Title"]',
    "strong",
    "span",
  ],
} as const;
