export const ORDERS_QA_ENTRY_SELECTORS = {
  shortcutRowSelectors: [
    ".d-grid.grid-cols-2.h-100",
    '[class*="d-grid"][class*="grid-cols-2"][class*="h-100"]',
  ],
  shortcutTileSelectors: [
    ".shortcut-item.cursor-pointer",
    ".shortcut-item",
    '[class*="shortcut-item"]',
    '[class*="cursor-pointer"]',
  ],
  directEntrySelectors: [
    'a:has-text("Orders and QA Management")',
    'a:has-text("Orders & QA Management")',
    'button:has-text("Orders and QA Management")',
    'button:has-text("Orders & QA Management")',
    '[role="link"]:has-text("Orders and QA Management")',
    '[role="link"]:has-text("Orders & QA Management")',
    '[role="button"]:has-text("Orders and QA Management")',
    '[role="button"]:has-text("Orders & QA Management")',
    '[class*="tile"]:has-text("Orders and QA Management")',
    '[class*="tile"]:has-text("Orders & QA Management")',
    '[class*="card"]:has-text("Orders and QA Management")',
    '[class*="card"]:has-text("Orders & QA Management")',
  ],
  containerAncestorSelectors: [
    '[class*="tile"]',
    '[class*="Tile"]',
    '[class*="card"]',
    '[class*="Card"]',
    '[class*="widget"]',
    '[class*="Widget"]',
    'section',
    'article',
    '[role="group"]',
    '[role="region"]',
  ],
  candidateContainerSelectors: [
    'main a',
    'main button',
    'main [role="link"]',
    'main [role="button"]',
    'main [class*="tile"]',
    'main [class*="Tile"]',
    'main [class*="card"]',
    'main [class*="Card"]',
    'main [class*="widget"]',
    'main [class*="Widget"]',
    'nav a',
    'nav button',
  ],
  nestedLabelSelectors: [
    'h1',
    'h2',
    'h3',
    'h4',
    '[role="heading"]',
    '[class*="title"]',
    '[class*="Title"]',
    'strong',
    'span',
  ],
  interactiveSelectors: [
    ".shortcut-item.cursor-pointer",
    '[class*="cursor-pointer"]',
    'a',
    'button',
    '[role="link"]',
    '[role="button"]',
    '[tabindex]:not([tabindex="-1"])',
  ],
} as const;

export const ORDERS_QA_ENTRY_PATTERNS = {
  exact: [/orders and qa management/i, /orders\s*&\s*qa management/i],
  loose: [/\borders?\b/i, /\bqa\b/i],
} as const;
