export const PAGE_TRANSITION_SELECTORS = {
  modalSelectors: [
    '[role="dialog"]',
    '[aria-modal="true"]',
    '[class*="modal"]',
    '[class*="Modal"]',
  ],
  splitViewSelectors: [
    '[class*="split"]',
    '[class*="Split"]',
    '[class*="pane"]',
    '[class*="Pane"]',
    '[class*="drawer"]',
    '[class*="Drawer"]',
    '[class*="sidepanel"]',
    '[class*="SidePanel"]',
  ],
  rootViewSelectors: [
    'main',
    '[role="main"]',
    '[class*="content"]',
    '[class*="Content"]',
    '[class*="view"]',
    '[class*="View"]',
  ],
  headingSelectors: [
    'main h1',
    'main h2',
    'main h3',
    '[role="dialog"] h1',
    '[role="dialog"] h2',
    '[role="dialog"] h3',
    '[role="heading"]',
  ],
  dashboardPersistenceSelectors: [
    'text="Add New Patient"',
    'text="Admission / Discharges"',
    'text="Event Calendar"',
    'text="Search Patient"',
  ],
  destinationSurfaceMarkers: [
    'text="Orders and QA Management"',
    'text="Orders & QA Management"',
    '[role="tablist"]',
    'table',
    '[role="grid"]',
    '[class*="board"]',
    '[class*="Board"]',
  ],
  commandPaletteSelectors: [
    '[role="dialog"] [role="searchbox"]',
    '[role="dialog"] input[type="search"]',
    '[class*="command"]',
    '[class*="Command"]',
    '[class*="palette"]',
    '[class*="Palette"]',
  ],
} as const;
