export const QA_QUEUE_SELECTORS = {
  queueUrlPattern: /\/document-tracking/i,
  queueQueryPattern: /page=forQA/i,
  queueMarkers: [
    'text="QA Monitoring"',
    "tr.fin-data-table__tr",
    "table tbody tr",
    '[role="row"]:has([role="cell"])',
    'text="View / Edit Note"',
  ],
  rowSelectors: [
    "tr.fin-data-table__tr",
    "table tbody tr",
    'tr[role="row"]',
    '[role="row"]:has([role="cell"])',
  ],
  headerCellSelectors: [
    "table thead th",
    '[role="columnheader"]',
  ],
  paginationSelectors: [
    "nav[aria-label*=\"pagination\"]",
    "ul.pagination",
    '[class*="pagination"]',
    '[class*="Pagination"]',
  ],
  nextPageSelectors: [
    'a[aria-label*="Next"]',
    'button[aria-label*="Next"]',
    'a[title*="Next"]',
    'button[title*="Next"]',
    'a:has-text("Next")',
    'button:has-text("Next")',
    '[role="button"]:has-text("Next")',
    '[role="link"]:has-text("Next")',
    'a[rel="next"]',
  ],
  pageNumberSelectors: [
    'a[aria-label*="Page"]',
    'button[aria-label*="Page"]',
    'a[href*="page="]',
    'button',
    'a',
    '[role="button"]',
    '[role="link"]',
  ],
  cellSelectors: ["td", '[role="cell"]'],
  patientLinkSelectors: [
    'a[href*="/client/"]:not([href*="/documents/"])',
    'a[href*="/patient/"]',
  ],
  documentDescSelectors: [
    'a[href*="/documents/"]:not([href*="/documents/note/visitnote/"])',
    "td:nth-child(2) a",
    "td:nth-child(3) a",
    "td:nth-child(2)",
    "td:nth-child(3)",
  ],
  actionSelectors: [
    "a",
    "button",
    '[role="link"]',
    '[role="button"]',
    '[ngbtooltip]',
    '.tooltip-div',
  ],
  actionCellSelectors: [
    "td:last-child",
    'td:has([ngbtooltip])',
    '[class*="action"]',
    '[class*="Action"]',
  ],
  noteOpenActionSelectors: [
    'a[ngbtooltip*="View / Edit Note"]',
    'a[title*="View / Edit Note"]',
    'a[aria-label*="View / Edit Note"]',
    'a:has-text("View / Edit Note")',
    '[ngbtooltip*="View / Edit Note"]',
    'button[title*="View / Edit Note"]',
    'button[aria-label*="View / Edit Note"]',
    '[role="link"][aria-label*="View / Edit Note"]',
    '[role="button"][aria-label*="View / Edit Note"]',
    'a[href*="/documents/note/visitnote/"]',
  ],
  actionLabelAttributeNames: [
    "ngbtooltip",
    "title",
    "aria-label",
    "data-tooltip",
    "data-label",
    "data-original-title",
    "mattooltip",
  ],
} as const;
