export const VISIT_NOTE_DETAIL_SELECTORS = {
  detailUrlPattern: /\/documents\/note\/visitnote\//i,
  orderDetailUrlPattern: /\/documents\/order\//i,
  trackedSectionIds: [
    "subjective-info",
    "diagnosis-history",
    "visit-summary",
    "safety-issues",
    "functional-mobility",
  ],
  headingSelectors: [
    "main h1",
    "main h2",
    '[role="heading"]',
    '[class*="title"]',
    '[class*="Title"]',
  ],
  sectionHeaderSelectors: [
    "main h2",
    "main h3",
    "main h4",
    "section h2",
    "section h3",
    '[role="heading"]',
    "legend",
  ],
  fieldLabelSelectors: [
    "label",
    "dt",
    "th",
    '[class*="label"]',
    '[class*="Label"]',
    '[class*="field-name"]',
    '[class*="FieldName"]',
  ],
  sectionHeadingSelectors: [
    "h1",
    "h2",
    "h3",
    "h4",
    "legend",
    '[role="heading"]',
    '[class*="heading"]',
    '[class*="Heading"]',
    '[class*="title"]',
    '[class*="Title"]',
  ],
  buttonSelectors: [
    "button",
    "a",
    '[role="button"]',
    '[role="link"]',
  ],
  textAreaSelectors: [
    "textarea",
    '[role="textbox"][aria-multiline="true"]',
  ],
  attachmentSelectors: [
    '[class*="attachment"]',
    '[class*="Attachment"]',
    'text=/attachment|related document/i',
  ],
  statusAreaSelectors: [
    '[class*="status"]',
    '[class*="Status"]',
    '[class*="signature"]',
    '[class*="Signature"]',
    '[data-testid*="signature"]',
    '[data-testid*="status"]',
    'text=/status|signature/i',
  ],
  signatureStateSelectors: [
    '[class*="signature"]',
    '[class*="Signature"]',
    '[class*="status"]',
    '[class*="Status"]',
    '[data-testid*="signature"]',
    '[data-testid*="status"]',
    'text=/signed|unsigned|signature/i',
  ],
  pageTitleSelectors: [
    "main h1",
    "main h2",
    '[role="heading"]',
    '[class*="title"]',
    '[class*="Title"]',
  ],
  detailMarkers: [
    'text=/visit note/i',
    'textarea',
    '[class*="signature"]',
    '[class*="status"]',
    '[class*="attachment"]',
  ],
  visitNoteIndicators: [
    "#subjective-info",
    "#diagnosis-history",
    "#visit-summary",
    "#safety-issues",
    'text=/visit summary|safety issues|diagnosis history/i',
  ],
  orderIndicators: [
    'text="Physician or Allowed Practitioner"',
    'text="Order Type"',
    'text=/medication/i',
  ],
  visitDateLabelPattern: /\b(visit date|date of visit|service date|dos)\b/i,
  signatureSignedPattern: /\b(signed|electronically signed|completed and signed)\b/i,
  signatureUnsignedPattern: /\b(unsigned|not signed|signature required|pending signature)\b/i,
} as const;
