import type { PatientEpisodeWorkItem } from "@medical-ai-qa/shared-types";
import type {
  ChartSnapshotValue,
  FieldMapSnapshot,
  ReferralFieldDefinition,
} from "./types";

export const REFERRAL_FIELD_CONTRACT: ReferralFieldDefinition[] = [
  {
    key: "patient_name",
    label: "Patient Name",
    category: "patient_identity_demographics",
    type: "text",
    control: "text_input",
    options: [],
    llm_fill_candidate: false,
    human_review_required: false,
    reference_only: true,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "dob",
    label: "Date of Birth",
    category: "patient_identity_demographics",
    type: "date",
    control: "date_picker",
    options: [],
    llm_fill_candidate: false,
    human_review_required: false,
    reference_only: true,
    compare_strategy: "date_equivalence",
    evidence_strategy: "direct_span",
  },
  {
    key: "soc_date",
    label: "Start of Care Date",
    category: "assessment_context",
    type: "date",
    control: "date_picker",
    options: [],
    llm_fill_candidate: false,
    human_review_required: false,
    reference_only: true,
    compare_strategy: "date_equivalence",
    evidence_strategy: "direct_span",
  },
  {
    key: "referral_date",
    label: "Referral Date",
    category: "assessment_context",
    type: "date",
    control: "date_picker",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "date_equivalence",
    evidence_strategy: "direct_span",
  },
  {
    key: "preferred_language",
    label: "Preferred Language",
    category: "patient_identity_demographics",
    type: "single_select",
    control: "select",
    options: [],
    llm_fill_candidate: true,
    human_review_required: false,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "interpreter_needed",
    label: "Interpreter Needed",
    category: "patient_identity_demographics",
    type: "boolean",
    control: "checkbox",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "presence_only",
    evidence_strategy: "direct_span",
  },
  {
    key: "primary_reason_for_home_health_medical_necessity",
    label: "Primary Reason for Home Health / Medical Necessity",
    category: "medical_necessity_homebound",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "section_summary",
  },
  {
    key: "admit_reason_to_home_health",
    label: "Admit Reason to Home Health",
    category: "medical_necessity_homebound",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "section_summary",
  },
  {
    key: "homebound_narrative",
    label: "Homebound Narrative",
    category: "medical_necessity_homebound",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "homebound_supporting_factors",
    label: "Homebound Supporting Factors",
    category: "medical_necessity_homebound",
    type: "multi_select",
    control: "multi_select",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "unordered_set_overlap",
    evidence_strategy: "cross_section",
  },
  {
    key: "recent_hospitalization_discharge_date",
    label: "Recent Hospitalization Discharge Date",
    category: "assessment_context",
    type: "date",
    control: "date_picker",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "date_equivalence",
    evidence_strategy: "direct_span",
  },
  {
    key: "recent_hospitalization_facility",
    label: "Recent Hospitalization Facility",
    category: "assessment_context",
    type: "text",
    control: "text_input",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "caregiver_name",
    label: "Caregiver Name",
    category: "living_situation_caregiver",
    type: "text",
    control: "text_input",
    options: [],
    llm_fill_candidate: true,
    human_review_required: false,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "caregiver_relationship",
    label: "Caregiver Relationship",
    category: "living_situation_caregiver",
    type: "single_select",
    control: "select",
    options: [],
    llm_fill_candidate: true,
    human_review_required: false,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "caregiver_phone",
    label: "Caregiver Phone",
    category: "living_situation_caregiver",
    type: "phone",
    control: "text_input",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
  {
    key: "living_situation",
    label: "Living Situation",
    category: "living_situation_caregiver",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: false,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "section_summary",
  },
  {
    key: "prior_functioning",
    label: "Prior Functioning",
    category: "risk_scores_and_function",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "functional_limitations",
    label: "Functional Limitations",
    category: "risk_scores_and_function",
    type: "multi_select",
    control: "multi_select",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "unordered_set_overlap",
    evidence_strategy: "cross_section",
  },
  {
    key: "therapy_need",
    label: "Therapy Need",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "section_summary",
  },
  {
    key: "patient_summary_narrative",
    label: "Patient Summary / Clinical Narrative",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "skilled_interventions",
    label: "Skilled Interventions",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "discipline_frequencies",
    label: "Discipline Frequencies",
    category: "therapy_plan_and_narrative",
    type: "array",
    control: "repeating_rows",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "presence_only",
    evidence_strategy: "section_summary",
  },
  {
    key: "plan_for_next_visit",
    label: "Plan For Next Visit",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "patient_caregiver_goals",
    label: "Patient / Caregiver Goals",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "care_plan_problems_goals_interventions",
    label: "Care Plan Problems / Goals / Interventions",
    category: "therapy_plan_and_narrative",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "fall_risk_narrative",
    label: "Fall Risk Narrative",
    category: "risk_scores_and_function",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "section_summary",
  },
  {
    key: "respiratory_status",
    label: "Respiratory Status",
    category: "immunization_neuro_psych_cardiopulmonary",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "integumentary_wound_status",
    label: "Integumentary / Wound Status",
    category: "nutrition_gi_gu_integument_safety",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "pain_assessment_narrative",
    label: "Pain Assessment Narrative",
    category: "pain_medications_allergies",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "emotional_behavioral_status",
    label: "Emotional / Behavioral Status",
    category: "immunization_neuro_psych_cardiopulmonary",
    type: "textarea",
    control: "textarea",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "narrative_support_compare",
    evidence_strategy: "cross_section",
  },
  {
    key: "past_medical_history",
    label: "Past Medical History",
    category: "past_medical_history",
    type: "array",
    control: "repeating_rows",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "unordered_set_overlap",
    evidence_strategy: "cross_section",
  },
  {
    key: "immunization_status",
    label: "Immunization / Vaccination Status",
    category: "immunization_neuro_psych_cardiopulmonary",
    type: "multi_select",
    control: "multi_select",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "unordered_set_overlap",
    evidence_strategy: "cross_section",
  },
  {
    key: "diagnosis_candidates",
    label: "Diagnosis Candidates",
    category: "active_diagnoses",
    type: "diagnosis_row",
    control: "repeating_rows",
    options: [],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "ranked_diagnosis_compare",
    evidence_strategy: "diagnosis_table",
  },
  {
    key: "code_status",
    label: "Code Status",
    category: "emergency_directives_cultural",
    type: "single_select",
    control: "radio_group",
    options: [
      { label: "Full Code", value: "full_code" },
      { label: "DNR", value: "dnr" },
      { label: "Unknown", value: "unknown" },
    ],
    llm_fill_candidate: true,
    human_review_required: true,
    reference_only: false,
    compare_strategy: "normalized_string",
    evidence_strategy: "direct_span",
  },
];

function normalizePhone(value: string): string {
  return value.replace(/\D+/g, "");
}

export function createInitialChartSnapshotValues(input: {
  workItem: PatientEpisodeWorkItem;
  currentChartValues?: Record<string, unknown>;
}): ChartSnapshotValue[] {
  const currentChartValues = input.currentChartValues ?? {};
  const patientName = input.workItem.patientIdentity.displayName || null;
  const socDate = input.workItem.episodeContext.socDate || null;

  return REFERRAL_FIELD_CONTRACT.map((field) => {
    let source: ChartSnapshotValue["source"] = "unavailable";
    let currentValue = currentChartValues[field.key] ?? null;

    if (currentValue !== null && currentValue !== undefined && currentValue !== "") {
      source = "chart_read";
    } else if (field.key === "patient_name" && patientName) {
      currentValue = patientName;
      source = "workbook_context";
    } else if (field.key === "soc_date" && socDate) {
      currentValue = socDate;
      source = "workbook_context";
    }

    if (field.key === "caregiver_phone" && typeof currentValue === "string") {
      currentValue = normalizePhone(currentValue);
    }

    return {
      fieldKey: field.key,
      currentValue,
      source,
      populated: currentValue !== null && currentValue !== undefined && currentValue !== "",
    };
  });
}

export function buildFieldMapSnapshot(input: {
  chartSnapshotValues: ChartSnapshotValue[];
}): FieldMapSnapshot {
  const byKey = new Map(input.chartSnapshotValues.map((value) => [value.fieldKey, value]));
  const fields = REFERRAL_FIELD_CONTRACT.map((field) => {
    const snapshot = byKey.get(field.key);
    return {
      ...field,
      currentChartValue: snapshot?.currentValue ?? null,
      currentChartValueSource: snapshot?.source ?? "unavailable",
      populatedInChart: snapshot?.populated ?? false,
    };
  });

  return {
    generatedAt: new Date().toISOString(),
    fields,
    already_populated_from_chart: fields
      .filter((field) => field.populatedInChart)
      .map((field) => field.key),
    candidate_fields_for_llm_inference_from_referral: fields
      .filter((field) => field.llm_fill_candidate)
      .map((field) => field.key),
    required_human_review_fields: fields
      .filter((field) => field.human_review_required)
      .map((field) => field.key),
    non_fillable_reference_only_fields: fields
      .filter((field) => field.reference_only)
      .map((field) => field.key),
  };
}
